okaryo/TabTabTab

dist/manifest.json, package.json, src/view/GroupedTabList.tsx, src/view/PinnedTabList.tsx, src/view/TabItem.tsx
* いい感じに調整
* グループ化されたタブのUIを修正
* 閉じるボタンの位置をいい感じに修正
* faviconのスタイルを調整
=> タブアイテムのスタイルを修正

.eslintrc.js, src/api/ChromeTabsAPI.ts, src/model/GroupedColor.ts, src/model/Tabs.ts, src/usecase/MoveToTabUseCase.ts, src/view/App.tsx, src/view/GroupedTabList.tsx, src/view/PinnedTabList.tsx, src/view/TabItem.tsx, src/view/TabList.tsx, src/view/WindowTabs.tsx, test/model/GroupId.test.ts, test/model/GroupedColor.test.ts, test/model/GroupedTabs.test.ts, test/model/PinnedTabs.test.ts, test/model/Tab.test.ts, test/model/TabId.test.ts, test/model/Tabs.test.ts, test/model/Window.test.ts, test/model/WindowId.test.ts, test/sample.test.ts
=> モデルのテストを追加

.eslintrc.js, .github/workflows/test-and-lint.yml, README.md, dist/manifest.json, package.json, src/api/ChromeTabsAPI.ts, src/model/GroupedColor.ts, src/model/GroupedTabs.ts, src/model/PinnedTabs.ts, src/model/Tabs.ts, src/usecase/MoveToTabUseCase.ts, src/view/App.tsx, src/view/GroupedTabList.tsx, src/view/PinnedTabList.tsx, src/view/TabItem.tsx, src/view/TabList.tsx, src/view/WindowTabs.tsx, test/model/GroupId.test.ts, test/model/GroupedColor.test.ts, test/model/GroupedTabs.test.ts, test/model/PinnedTabs.test.ts, test/model/Tab.test.ts, test/model/TabId.test.ts, test/model/Tabs.test.ts, test/model/Window.test.ts, test/model/WindowId.test.ts, test/sample.test.ts
* バージョン２をリリースしたけど、いろいろ気になることがあったので修正
=> version2.0.1

src/api/ChromeTabsAPI.ts, src/view/TabItem.tsx
=> タブ移動できない問題の修正

src/model/GroupedTabs.ts, src/model/NestedTabs.ts, src/model/PinnedTabs.ts, src/model/Tabs.ts, src/view/TabList.tsx
=> NestedTabsインターフェースの作成

package-lock.json, src/model/GroupedColor.ts, test/model/GroupedColor.test.ts
=> グループにオレンジ色を追加

src/model/Tabs.ts, test/factory/TabFactory.ts, test/model/Window.test.ts
=> タブ削除時のバグ修正

dist/_locales/fr/messages.json
=> Translation to other languages: fr

dist/_locales/de/messages.json, src/i18n/Translations.ts
=> Add german translation

dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/repository/ChromeStorage.ts, src/repository/SettingsRepository.ts, src/view/features/options/PopupElementScaleSettingForm.tsx, src/view/features/options/PopupSizeSettingForm.tsx, src/view/features/options/Settings.tsx, src/view/features/popup/components/GroupedTabList.tsx, src/view/features/popup/components/PinnedTabList.tsx, src/view/features/popup/components/TabItem.tsx, src/view/features/popup/components/ThemeProvider.tsx, src/view/features/popup/pages/App.tsx
=> Add capability to change font size

dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json
=> Add translations for en_US and en_GB

src/view/features/popup/components/Header.tsx, src/view/features/popup/components/TabItem.tsx, src/view/features/popup/pages/Home.tsx
=> Enable Arrow-Key-Selection and Enter-Key-Navigation in tab search results

.github/workflows/generate-release-note.yml
=> Generate release note on tag push

src/view/features/popup/components/TabItem.tsx
=> Show tab title tooltip on mouse hover

src/view/features/popup/components/Header.tsx
=> Improve search field visibility

src/view/features/popup/pages/Home.tsx
=> Enable window navigation in popup using right and left arrow keys

src/view/features/popup/components/SearchResult.tsx, src/view/features/popup/components/WindowTabs.tsx, src/view/features/popup/pages/Home.tsx
=> Fixed issue where no results were displayed when search returned zero matches

src/view/features/popup/components/GroupedTabList.tsx, src/view/features/popup/components/PinnedTabList.tsx, src/view/features/popup/components/ThemeProvider.tsx
=> Show tab count on group and pin headers

src/view/features/popup/components/GroupedTabList.tsx
=> Fix group tab count position when group title is empty

src/model/Tab.ts, src/repository/WindowsRepository.ts
use `pendingUrl` when `url` is empty or undefined
=> Enable showing tabs even when a page is still loading

src/view/features/popup/components/WindowTabs.tsx
Thanks: https://github.com/okaryo/TabTabTab/discussions/89#discussioncomment-6562103
=> Fix the incorrect tab count displayed beside the window tab

.github/renovate.json, src/view/components/ThemeProvider.tsx, src/view/features/options/App.tsx, src/view/features/options/Feedback.tsx, src/view/features/options/Header.tsx, src/view/features/options/PopupElementScaleSettingForm.tsx, src/view/features/options/PopupSizeSettingForm.tsx, src/view/features/options/Settings.tsx, src/view/features/options/TabCleanerSettingForm.tsx, src/view/features/options/index.tsx, src/view/features/popup/components/GroupedTabList.tsx, src/view/features/popup/components/Header.tsx, src/view/features/popup/components/PinnedTabList.tsx, src/view/features/popup/components/SearchResult.tsx, src/view/features/popup/components/TabActionMenu.tsx, src/view/features/popup/components/TabFavicon.tsx, src/view/features/popup/components/TabItem.tsx, src/view/features/popup/components/TabList.tsx, src/view/features/popup/components/ThemeProvider.tsx, src/view/features/popup/components/WindowTab.tsx, src/view/features/popup/components/WindowTabs.tsx, src/view/features/popup/index.tsx, src/view/features/popup/pages/App.tsx, src/view/features/popup/pages/Home.tsx, tsconfig.json
=> Refactor config

src/model/Tab.ts, src/repository/WindowsRepository.ts, src/view/features/popup/components/TabActionMenu.tsx
=> Fix an invisibility of menu when tab count is one

dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/model/Tab.ts, src/repository/TabsRepository.ts, src/view/features/popup/components/TabActionMenu.tsx, src/view/features/popup/hooks/usePinTab.ts, src/view/features/popup/hooks/useUnpinTab.ts
=> Unpin a pinned tab

src/view/features/popup/components/TabList.tsx
=> Fix issue where selecting a different window in the popup doesn't navigate

.github/workflows/test-and-lint.yml, src/model/Tab.ts, src/model/TabContainer.ts, src/model/Window.ts, src/repository/WindowsRepository.ts, src/view/features/popup/components/GroupedTabList.tsx, src/view/features/popup/components/TabItem.tsx, src/view/features/popup/components/TabList.tsx, src/view/features/popup/hooks/useCollapseTabGroup.ts, src/view/features/popup/hooks/useExpandTabGroup.ts, test/factory/TabContainerFactory.ts, test/factory/TabFactory.ts, test/factory/WindowFactory.ts, test/model/Tab.test.ts, test/model/TabContainer.test.ts, test/model/Window.test.ts
* Improve tab visibility when dragged
* Improve behavior when item is dropped
* Add tests
* Refactor codes
=> Improve Drag and Drop behavior

src/view/features/popup/components/SortableItem.tsx, src/view/features/popup/components/SortableTabs.tsx, src/view/features/popup/components/TabList.tsx, src/view/features/popup/components/WindowTabs.tsx, src/view/features/popup/components/WindowsContainer.tsx, src/view/features/popup/hooks/useWindows.ts, src/view/features/popup/pages/Home.tsx
=> Refactor Selected Index in Window and Sortable Item

src/view/features/popup/components/SortableItem.tsx, src/view/features/popup/components/TabGroupContainer.tsx, src/view/features/popup/components/TabItem.tsx, src/view/features/popup/components/TabList.tsx
* Show grabbing mouse cursor when item is dragged
* Show drag indicator icon when item is hovered
=> Show grabbing mouse cursor and drag indicator icon when draggable item is selected

dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/repository/TabGroupRepository.ts, src/view/features/popup/components/TabActionMenu.tsx, src/view/features/popup/components/TabGroupActionMenu.tsx, src/view/features/popup/components/TabGroupContainer.tsx, src/view/features/popup/components/TabItem.tsx, src/view/features/popup/hooks/useCloseTabGroup.tsx, src/view/features/popup/hooks/useUngroup.ts
=> TabGroup Actions to Ungroup and Close Group

src/view/features/popup/components/PinnedContainer.tsx, src/view/features/popup/components/TabList.tsx
`destIndex`が0のとき、`!destIndex`がtrueになってた
=> Fix dropping behavior when item is dropped on index 0

src/view/features/popup/components/WindowTabs.tsx
=> Show horizontal scroll button for window tabs

dist/_locales/bg/messages.json
Adding translation to Bulgarian language.
=> Create messages.json -> Bulgarian translation

src/model/Tab.ts, src/model/Window.ts, src/repository/TabGroupRepository.ts, src/repository/TabsRepository.ts, src/view/features/popup/components/SortableItem.tsx, src/view/features/popup/components/SortableTabs.tsx, src/view/features/popup/components/TabList.tsx, src/view/features/popup/components/WindowTab.tsx, src/view/features/popup/components/WindowTabs.tsx, src/view/features/popup/components/WindowsContainer.tsx, src/view/features/popup/hooks/useMoveTabGroupToOtherWindow.ts, src/view/features/popup/hooks/useMoveTabToOtherWindow.ts
like this
https://github.com/okaryo/TabTabTab/assets/44517313/ec70ee4e-355c-4cf6-b5f7-22d09abedb6a
=> Enable Moving Tabs and Tab Groups to Other Window With Drag&Drop

package-lock.json, package.json
=> deps: Update Vite to v5

src/model/GroupColor.ts, src/repository/TabGroupRepository.ts, src/view/features/popup/components/TabGroupContainer.tsx, src/view/features/popup/hooks/useUpdateTabGroupColor.ts
like this
https://github.com/okaryo/TabTabTab/assets/44517313/1fd38538-88b0-4f35-8ab1-3dc90ea3f8ba
=> Enable to Change Tab Group Color

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/repository/TabsRepository.ts, src/repository/WindowsRepository.ts, src/view/features/popup/components/ActionMenu.tsx, src/view/features/popup/hooks/useAddTabToNewGroup.ts, src/view/features/popup/hooks/useRemoteFromTabGroup.ts
=> Enable to Add or Remove Tabs from Groups via Action Menu

src/background/KeyboardShortcuts.ts, src/background/index.ts, src/view/features/popup/pages/App.tsx
like this
https://github.com/okaryo/TabTabTab/assets/44517313/55bcebd4-f15a-4b70-8e19-8809c76cd540
=> Close Popup When Other Window is Focused

.github/renovate.json, src/model/settings/PopupSize.ts, src/repository/SettingsRepository.ts
popup size: 500\*400 → 600\*400
element scale: 100% → 80%
=> Change default popup size and default element scale

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/background/TabActivityTracker.ts, src/i18n/Translations.ts, src/repository/ChromeStorage.ts, src/repository/SettingsRepository.ts, src/repository/TabsRepository.ts, src/repository/ThemeRepository.ts, src/repository/WindowsRepository.ts, src/view/features/popup/components/SearchResult.tsx, src/view/features/popup/components/TabItem.tsx
like this
https://github.com/okaryo/TabTabTab/assets/44517313/098b18fe-8a1e-4aba-9dfe-17367383b2ca
=> Show Recently Active Tabs in Search Results, Including Closed Tabs

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, dist/manifest.json, src/i18n/Translations.ts, src/repository/TabsRepository.ts, src/view/features/popup/components/ActionMenu.tsx
=> Remove Bookmark Tab Feature

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json
=> Filled in the 'description' field in the locale file

src/view/features/popup/components/TabItem.tsx
=> Changed URL Display to Show Only the Host Part

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/model/Tab.ts, src/model/Window.ts, src/repository/TabsRepository.ts, src/view/features/popup/components/TabItem.tsx, src/view/features/popup/hooks/useResolveDuplicateTabs.ts
https://github.com/okaryo/TabTabTab/assets/44517313/e89cb70a-bbc1-48ed-8608-d893d39a82a3
=> Easily Close All Non-Selected Duplicates with One Click

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/model/Window.ts, src/repository/TabsRepository.ts, src/view/components/ActionMenu.tsx, src/view/features/options/pages/Overview/index.tsx, src/view/hooks/useAddTabToNewGroup.ts, src/view/hooks/useMergeWindow.ts
demo
https://github.com/okaryo/TabTabTab/assets/44517313/406b6b3b-e9cd-4f19-b9c4-a3ec25aace53
=> Enable Window Merging on Overview Page

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/view/features/options/App.tsx, src/view/features/popup/components/Home.tsx
* Overview → All Windows
* Restore
* Settings
* Feedback
=> Setup locales for navigation headers in options page

src/view/features/popup/components/Header.tsx, src/view/features/popup/components/Home.tsx
=> Add Clear Button to Search Field When Typing

src/view/features/popup/components/WindowTab.tsx, src/view/features/popup/components/WindowTabs.tsx
=> Enable Window Actions in Popup

README.md, dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/view/features/options/App.tsx, src/view/features/options/pages/Settings/PopupElementScaleSettingForm.tsx, src/view/features/options/pages/Settings/PopupSizeSettingForm.tsx, src/view/features/options/pages/Settings/TabCleanerSettingForm.tsx, src/view/features/options/pages/Sponsor/index.tsx
=> Add Sponsor Page

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, dist/manifest.json, dist/side_panel.html, src/i18n/Translations.ts, src/model/TabContainer.ts, src/repository/SettingsRepository.ts, src/repository/TabsRepository.ts, src/view/components/ActionMenu.tsx, src/view/features/popup/App.tsx, src/view/features/popup/components/Header.tsx, src/view/features/popup/components/Home.tsx, src/view/features/sidePanel/index.tsx, vite.config.ts
=> Enable use on SidePanel

src/model/Tab.ts, src/repository/ChromeStorage.ts, src/repository/TabsRepository.ts, src/view/components/TabFavicon.tsx, src/view/components/TabItem.tsx
=> Reflect tab states like `loading` and `discarded` in Favicon

dist/_locales/ja/messages.json, src/view/components/TabItem.tsx
=> Fix Missing Elapsed Time Display for Newly Activated Tabs

src/repository/SettingsRepository.ts, src/view/components/ActionMenu.tsx, src/view/features/popup/components/Header.tsx
=> Avoid Header Rebuild on Tab Update

src/view/components/RestorePage/StoredTabGroups.tsx, src/view/components/TabGroupContainer.tsx
=> Update text color in group name field for improved contrast

src/view/components/TabItem.tsx
=> Fix Favicon Size Shrinking During Loading with Long Tab Titles

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/model/Mode.ts, src/model/Theme.ts, src/repository/ChromeStorage.ts, src/repository/ThemeRepository.ts, src/view/components/RestorePage/StoredTabGroups.tsx, src/view/components/TabGroupColorRadio.tsx, src/view/components/TabGroupContainer.tsx, src/view/contexts/ModeContext.tsx, src/view/contexts/ThemeColorContext.tsx, src/view/features/options/App.tsx, src/view/features/options/pages/Feedback/index.tsx, src/view/features/options/pages/Overview/index.tsx, src/view/features/options/pages/Settings/ThemeColorSettingForm.tsx, src/view/features/options/pages/Settings/index.tsx, src/view/features/popup/App.tsx, src/view/features/popup/components/MuiThemeProvider.tsx, src/view/features/popup/components/WindowTab.tsx, src/view/resources/tabGroupColorPalette.ts, src/view/resources/themeColorPalette.ts
=> Enable setting a theme color for TabTabTab

src/view/components/TabFavicon.tsx, src/view/components/TabItem.tsx
=> Handle errors fetching favicon and loading spinner in new tabs

src/background/AutoTabGrouping.ts
=> Auto-group tabs when moving between windows

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/data/repository/TabsRepository.ts, src/i18n/Translations.ts, src/view/components/ActionMenu.tsx, src/view/components/TabFavicon.tsx
* Enable duplicate tabs from tab action menu
* Refine sponsor page text
=> Enable duplicate tabs from tab action menu

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/background/AutoTabGrouping.ts, src/data/repository/TabGroupRepository.ts, src/data/repository/TabGroupSettingRepository.ts, src/i18n/Translations.ts, src/model/TabGroupSetting.ts, src/view/components/OrganizationPage/TabGroupingForm.tsx
=> Enable Sorting Groups Alphabetically

package.json, src/background/index.ts, src/vite-env.d.ts, tsconfig.json
=> Show `DEV` badge text when development mode

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/view/components/ActionMenu.tsx, src/view/features/popup/components/Header.tsx, src/view/features/popup/components/WindowTabs.tsx
=> Add rate & review, join discussions, and sponsor project to header action menu

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, package-lock.json, src/data/repository/WindowsRepository.ts, src/i18n/Translations.ts, src/view/components/ActionMenu.tsx
=> Add `Save All Windows` option to action menu for multiple open windows

src/view/components/RestorePage/StoredTabItem.tsx
=> Show tab title on hover saved tabs

.github/RELEASE_PULL_REQUEST_TEMPLATE.erb, .github/workflows/create-release-pull-request.yml
ref: https://github.com/x-motemen/git-pr-release
=> Create release pull request by github actions on merge to develop branch

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/data/repository/TabGroupRepository.ts, src/data/repository/WindowsRepository.ts, src/i18n/Translations.ts, src/view/components/RestorePage/AddTabFrom.tsx, src/view/components/RestorePage/StoredTabGroups.tsx, src/view/components/RestorePage/StoredWindows.tsx, src/view/hooks/useDebounce.ts
=> Enable to Add New Tabs to Saved Groups/Windows

.github/RELEASE_PULL_REQUEST_TEMPLATE.erb, .github/workflows/create-release-pull-request.yml
=> Change Release PullRequest Title TimeZone to UTC

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/view/components/RestorePage/StoredWindows.tsx, src/view/features/options/App.tsx
=> Enable to Save Current Window in Restore Page

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/data/repository/TabGroupRepository.ts, src/data/repository/TabsRepository.ts, src/i18n/Translations.ts, src/model/Window.ts, src/view/features/popup/components/SearchResult.tsx, src/view/functions/groupTabsBySearchKeyword.ts, test/model/Window.test.ts
=> Group Search Result Tabs by Search Keyword

src/view/components/TabItem.tsx, src/view/features/popup/components/SearchResult.tsx
=> Display pinned label and icon for pinned tabs in search results

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json
=> Add missing locale for `week`

dist/manifest.json, src/background/ToolBarAction.ts, src/background/index.ts, src/view/components/OrganizationPage/TabGroupingForm.tsx
* Save Current Window
* Group Tabs Now
* Open Dashboard
=> Add actions to toolbar icon's right-click menu

src/presentation/functions/groupTabsBySearchKeyword.ts
=> Fix issue with grouping tabs by search keyword

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/validate-release.yml
To prevent forgetting to update the version.
=> Verify manifest version update before release

.github/workflows/create-tag-and-release-note.yml, .github/workflows/release.yml
=> Add workflow to create tag and release note on merge release pull request

src/model/AsyncState.ts, src/presentation/contexts/StoredTabGroupsContext.tsx, src/presentation/contexts/StoredWindowsContext.tsx, src/presentation/hooks/useAsync.ts, src/presentation/hooks/useDebounce.ts, src/presentation/views/shared/components/SaveAndRestorePage/AddTabFrom.tsx, src/presentation/views/shared/components/SaveAndRestorePage/StoredTabGroups.tsx, src/presentation/views/shared/components/SaveAndRestorePage/StoredTabItem.tsx, src/presentation/views/shared/components/SaveAndRestorePage/StoredTabItemContainer.tsx, src/presentation/views/shared/components/SaveAndRestorePage/StoredWindows.tsx
=> Fix EmptyState UI flash during SavedWindows/Groups fetch by handling async state

package-lock.json, src/background/ToolBarAction.ts, src/presentation/views/popup/components/WindowTab.tsx, src/presentation/views/shared/components/TabItem.tsx
* Fix react dom nesting warning to apply component props
* Fix contextMenu id collision between dev and prodction extension by adding prefix to id
=> Fix warning of react dom nesting and contextMenu id collision

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/background/ToolBarAction.ts, src/data/repository/SettingsRepository.ts, src/data/repository/ToolbarRepository.ts, src/data/storage/ChromeLocalStorage.ts, src/i18n/Translations.ts, src/model/ToolbarSetting.ts, src/presentation/views/options/pages/Settings/ToolbarSettingForm.tsx, src/presentation/views/options/pages/Settings/index.tsx
=> Add setting to open dashboard on toolbar icon click

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/background/ToolBarAction.ts, src/data/repository/ToolbarRepository.ts, src/data/storage/ChromeLocalStorage.ts, src/i18n/Translations.ts, src/model/ToolbarSetting.ts, src/presentation/views/options/pages/Settings/ToolbarSettingForm.tsx
=> Add sidePanel option for toolbar icon click behavior

dist/_locales/bg/messages.json, dist/_locales/de/messages.json, dist/_locales/en/messages.json, dist/_locales/en_GB/messages.json, dist/_locales/en_US/messages.json, dist/_locales/fr/messages.json, dist/_locales/ja/messages.json, dist/_locales/ko/messages.json, dist/_locales/pl/messages.json, src/i18n/Translations.ts, src/presentation/views/shared/components/ActionMenu.tsx, src/presentation/views/shared/components/SaveAndRestorePage/StoredTabGroups.tsx, src/presentation/views/shared/components/SaveAndRestorePage/StoredWindows.tsx
like this
Also fixed an issue where the group edit form was breaking.
https://github.com/okaryo/TabTabTab/discussions/361#discussioncomment-11590080
=> Display Actions for StoredWindow/Group in a Menu

src/presentation/views/options/components/Header.tsx, src/presentation/views/popup/components/SearchResult.tsx
* open search dialog on click or keydown `/`
=> Enable to Search Tabs in Dashboard

dist/_locales/fa/messages.json
The app has been translated to Persian.
=> Added Persian Translation

.github/workflows/ci.yml
* to run pull requests from forked repos
=> Add `pull_request` event trigger to run ci workflow

.github/workflows/ci.yml, .github/workflows/create-release-pull-request.yml, .github/workflows/release.yml, .github/workflows/validate-release.yml
=> Replace github action version tag with hash
